[window]
dynamic_padding = true
decorations = "None"
opacity = 0.95

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control"
